//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;


namespace Caravan
{
	public class SelectionInterfaceHandler : MonoBehaviour
	{
		// SINGLETON
		static SelectionInterfaceHandler instance;

		public static SelectionInterfaceHandler GetInstance(){

			if (instance == null)
				instance = FindObjectOfType<SelectionInterfaceHandler> ();

			return instance;

		}

		private GameElement selected_element;

		public Text selected_name;

		public Text selected_damage;
		public Text selected_damage_value;

		public Text selected_health;
		public Text selected_health_value;

		public Text selected_range;
		public Text selected_range_value;

		public Button upgrade_button;
		public Text upgrade_button_text;

		public void Clear(){
			selected_element = null;

			EnableName (false);
			EnableDamage (false);
			EnableHealth (false);
			EnableRange (false);
			EnableUpgradeButton (false);
		}

		public void SelectElement(GameElement element){
			Clear ();
			selected_element = element;

			EnableName (true);
			selected_name.text = element.name_string;
		}

		// ENABLE / DISABLE ELEMENTS

		public void EnableName(bool en){
			selected_name.enabled = en;
		}

		public void EnableDamage(bool en){
			selected_damage.enabled = en;
			selected_damage_value.enabled = en;
		}

		public void EnableHealth(bool en){
			selected_health.enabled = en;
			selected_health_value.enabled = en;
		}

		public void EnableRange(bool en){
			selected_range.enabled = en;
			selected_range_value.enabled = en;
		}

		public void EnableUpgradeButton(bool en){
			upgrade_button.gameObject.SetActive(en);
		}

		// UPDATE ELEMENT VALUES

		public void UpdateName(string name_string){

			selected_name.text = name_string;

		}

		public void UpdateDamage(int value){

			//string damage_string = damage.ToString ();
			selected_damage_value.text = value.ToString ();
		
		}

		public void UpdateHealth(int value){
			
			//string damage_string = value.ToString ();
			selected_health_value.text = value.ToString();
			
		}

		public void UpdateRange(float value){
			
			//string damage_string = value.ToString ();
			selected_range_value.text = value.ToString();
			
		}

		public void UpdateButton(int value){

			upgrade_button_text.text = "Upgrade: (" + value.ToString () + ")";
			
		}

		// TODO MORE ELEMENT VALUES

		void LateUpdate(){
			if (selected_element != null) {

				selected_element.UpdateSelection ();

			} else
				Clear ();

		}

		public void PressUpgrade(){
			if (selected_element != null)
				selected_element.Upgrade ();
		}


	}
}

