//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;

namespace Interface
{
	public class SliderMenu : MonoBehaviour
	{

		public RectTransform[] scenes;
		public float transition_speed;
		public Transform move;

		int current_scene = 0;

		void Awake(){


		}

		public void Transition (int target){

			target = Mathf.Clamp (target, 0, scenes.Length);
			//move = scenes [0];
			StartCoroutine (CoroutineMoveCanvas (target));

			current_scene = target;

		}

		IEnumerator CoroutineMoveCanvas(int target){
			
			Vector3 starting_position = move.transform.position;
			Vector2 target_position = scenes[target].position;
			
			float lerp = 0.0f;
									
			while (lerp <= 1f) {
				
				lerp += transition_speed;

				Vector2 new_pos2d = Vector2.Lerp(starting_position, target_position, lerp);
				Vector3 new_pos3D = new Vector3(new_pos2d.x, new_pos2d.y, starting_position.z);

				move.GetComponent<Transform>().position = new_pos3D;
				
				yield return 0;
				
			}
			
			move.transform.position = new Vector3 (target_position.x, target_position.y, starting_position.z);
	
		}


	}
}

