//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Caravan
{
	public class BehaviourTrajectoryToTarget : GameElementBehaviour
	{
		BehaviourMoverTrajectory trajectory_mover;
		BehaviourMoverTarget target_mover;

		public BehaviourMoverTrajectory TrajectoryMover {
			get {
				return trajectory_mover;
			}
			set {
				trajectory_mover = value;
			}
		}

		public BehaviourMoverTarget TargetMover {
			get {
				return target_mover;
			}
			set {
				target_mover = value;
			}
		}

		BehaviourMover CurrentBehaviour;

		public BehaviourTrajectoryToTarget (GameElement parent, Trajectory trajectory, GameObject target, float speed ) : base(parent)
		{
			trajectory_mover = new BehaviourMoverTrajectory (parent, trajectory, speed, false);
			target_mover 	 = new BehaviourMoverTarget (parent, target, speed, false);

			CurrentBehaviour = trajectory_mover;

		}

		public override void GameElementFixedUpdate (){

			CurrentBehaviour.GameElementFixedUpdate ();

			if (CurrentBehaviour.ReachedDestination)
				CurrentBehaviour = target_mover;

		}


	}
}

