//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace Caravan
{
	public class BehaviourBounty : GameElementBehaviour
	{
		int _score_bounty;
		int _resource_bounty;


		public BehaviourBounty (GameElement parent, int score_bounty, int resource_bounty) : base(parent){
			
			_score_bounty = score_bounty;
			_resource_bounty = resource_bounty;
			
		}

		public override void GameElementOnDestroy (bool was_killed){

			if (was_killed) {
				GameController controller = GameController.GetInstance();

				controller.Score += _score_bounty;
				controller.Resources += _resource_bounty;
			}
		}

		// TODO upgrade behaviour

	}
}

