//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;


namespace Caravan
{
	public class BehaviourDoDamageTag : GameElementBehaviour
	{
		int _damage_value;
		string _target_tag;

		float _destroy_timer = 0;

		public BehaviourDoDamageTag (GameElement parent, string target_tag, int damage_value) : base(parent){

			_damage_value = damage_value;
			_target_tag = target_tag;

		}

		public void SetDestroyTimer (float destroy_timer)
		{
			_destroy_timer = destroy_timer;
		}

		public override void GameElementTrigger(Collider2D other){
			if (other.gameObject.tag == _target_tag) {

				other.SendMessage("GetHit", _damage_value);
				_parent.DestroyGameElement(0, false);

			}
		}

		public override void GameElementCollide(Collision2D coll){

			Parent.DestroyGameElement (_destroy_timer, false);

		}

	}
}

