//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace Caravan
{
	public class BehaviourRotateToDirection : GameElementBehaviour
	{
		protected Rigidbody2D rigidbody = null;

		Vector2 _rotation_treshold;

		bool rotate = true;

		public BehaviourRotateToDirection(GameElement parent) : base(parent){

			_rotation_treshold = GameController.GetInstance().Rotation_Treshold;
			rigidbody = parent.gameObject.GetComponent<Rigidbody2D> ();

		}

		public override void GameElementFixedUpdate (){

			if (rotate)
				UpdateRotation();
		}

		void UpdateRotation(){

			Vector3 dir = rigidbody.velocity;

			float angle = Mathf.Atan2 (dir.y, dir.x) * Mathf.Rad2Deg;
			Parent.transform.rotation = Quaternion.AngleAxis (angle, Vector3.forward);

		}

		public override void GameElementTrigger(Collider2D other){}

		public override void GameElementOnDestroy (bool was_killed){}

		public override void GameElementCollide (Collision2D collision){

			rotate = false;
		}


	}
}

