//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace Caravan
{
	public class BehaviourGatherer : GameElementBehaviour
	{

		private float _gather_frequency;
		private int _gather_amount;

		float gather_timer;

		public float Gather_frequency {
			get {
				return _gather_frequency;
			}
			set {
				_gather_frequency = value;
			}
		}

		public int Gather_amount {
			get {
				return _gather_amount;
			}
			set {
				_gather_amount = value;
			}
		}

		public BehaviourGatherer (GameElement parent,
		                         float gather_frequency,
		                          int gather_amount) : base (parent)
		{
			_gather_frequency 	= gather_frequency;
			_gather_amount 		= gather_amount;

			gather_timer = gather_frequency;
			
		}

		void TickGatherTimer(){
			
			gather_timer -= Time.fixedDeltaTime;
			
			if (gather_timer <= 0) {
				GatherResource ();
				gather_timer = _gather_frequency;
			}
			
		}

		void GatherResource(){

			GameController.GetInstance ().Resources += Gather_amount;

			Parent.FlashColor (Color.green, 1f);

		}

		public override void GameElementFixedUpdate (){
			base.GameElementFixedUpdate ();

			TickGatherTimer ();

		}

		//public virtual void GameElementUpdateSelection() {}
		//public virtual void GameElementTouch(){}
		public override void GameElementUpgrade(GameElementBehaviour upgrade_behaviour){

			BehaviourGatherer gatherer_behaviour = upgrade_behaviour as BehaviourGatherer;

				
			_gather_frequency = gatherer_behaviour._gather_frequency;
			_gather_amount 		= gatherer_behaviour._gather_amount;

		}

	}
}

