//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace Caravan
{
	public class BehaviourMoverTrajectory : BehaviourMover
	{
		//float _speed = 1.0f;
		Trajectory _trajectory;

		Waypoint waypoint;

		//Rigidbody2D rigidbody = null;

		public void SetTrajectory(Trajectory trajectory){

			if (trajectory != null) {
				_trajectory = trajectory;
				waypoint = trajectory.FirstPoint ();
			}

		}

		public BehaviourMoverTrajectory (GameElement parent, Trajectory trajectory, float speed, bool use_velocity) :  
			base(parent, speed, use_velocity)
		{
			//SetTrajectory (trajectory);

			rigidbody.drag = 1.0f;

		}

		public override void GameElementFixedUpdate (){

			if (rigidbody == null || _trajectory == null || ReachedDestination)
				return;

			MoveTowards(waypoint.Position);

			if (Vector2.Distance (waypoint.Position, _parent.transform.position) < Speed){
				waypoint = _trajectory.NextPoint(waypoint);
				
			}

			if (waypoint == null)
				ReachedDestination = true;

		}

	}
}

