//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;


namespace Caravan
{
	public class BehaviourDoDamageTarget : GameElementBehaviour
	{
		int _damage_value;
		GameObject _target;

		public BehaviourDoDamageTarget (GameElement parent, GameObject target, int damage_value) : base(parent){

			_damage_value = damage_value;
			_target = target;

		}

		public void SetTarget(GameObject target){
			_target = target;
		}

		public override void GameElementTrigger(Collider2D other){
			if (other.gameObject == _target) {

				other.SendMessage("GetHit", _damage_value);
				_parent.DestroyGameElement(0, false);

			}
		}

		public override void GameElementUpdateSelection() {
			SelectionInterfaceHandler.GetInstance ().UpdateDamage (_damage_value);
		}

		public override void GameElementTouch(){
			SelectionInterfaceHandler.GetInstance ().EnableDamage (true);
		}

		public override void GameElementUpgrade(GameElementBehaviour upgrade_behaviour){

			BehaviourDoDamageTarget damage_behaviour = upgrade_behaviour as BehaviourDoDamageTarget;

			_damage_value = damage_behaviour._damage_value;

		}

	}
}

