//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace Caravan
{
	public abstract class GameElementBehaviour
	{
		protected GameElement _parent;

		public GameElement Parent {
			get {
				return _parent;
			}
			set {
				_parent = value;
			}
		}

		public GameElementBehaviour (GameElement parent){
			_parent = parent;
		}

		public virtual void GameElementUpdate (){}
		public virtual void GameElementFixedUpdate (){}
		public virtual void GameElementLateUpdate (){}
		public virtual void GameElementTrigger(Collider2D other){}
		public virtual void GameElementCollide(Collision2D collision){}
		public virtual void GameElementDamage (int value){}
		public virtual void GameElementOnDestroy (bool was_killed){}
		public virtual void GameElementUpdateSelection() {}
		public virtual void GameElementTouch(){}
		public virtual void GameElementUpgrade(GameElementBehaviour upgrade_behaviour){}

	}
}

