//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

using SoundSystem;


namespace Caravan
{
	public class MainController : MonoBehaviour
	{
		public static MainController instance;

		//private bool sound = false;
		//private bool music = true;

		private SoundController sound_controller_ref;

		public bool Sound {
			get {
				return sound_controller_ref.Sound;
			}

		}

		public bool Music {
			get {
				return sound_controller_ref.Music;
			}

		}
		
		void Awake()
		{
			if(instance != null)
				GameObject.Destroy(instance);
			else
				instance = this;
			
			DontDestroyOnLoad(this);

			sound_controller_ref = SoundController.GetInstance ();
		}

		public void SwitchOption(bool is_on, Interface.ToggleType option ){
			
			switch (option) {
				
			case Interface.ToggleType.Music:

				sound_controller_ref.Music = is_on;
				break;
				
			case  Interface.ToggleType.Sound:

				sound_controller_ref.Sound = is_on;
				break;
			}

			Debug.Log (option.ToString() + " is now " + is_on);
			
		}

		// UNUSED
		// SOUND METHODS GO HERE

//		public void SoundSetClip(AudioClip audio){
//			
//			sound_controller_ref.SetMusic (audio);
//		}
//		
//		public void SoundPlayClip(){
//			
//			sound_controller_ref.PlayMusic ();
//		}
//		
//		public void SoundStopClip(){
//			sound_controller_ref.StopMusic ();
//		}
//		
//		public void SoundPauseClip(bool pause){
//			sound_controller_ref.PauseMusic (pause);
//
//		}
//		
//		public void SoundPlayClipOneShot(AudioClip audio){
//			
//			if (sound)
//				sound_controller_ref.PlayBGS (audio);
//		}


	


	}
}

