//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Caravan
{
	public class GE_Auto_Projectile : GameElement
	{
		public float speed;
		public float destroy_timer;
		private int damage;

		protected override void Awake(){
			base.Awake ();

			name_string = "Basic Projectile";
		}

		public void SetDamage(int dam){
			damage = dam;
		}

		public void SetTarget(GameObject target){

			if (target != null) {

				BehaviourMoverTarget mover = new BehaviourMoverTarget(this,target,speed, true);
				mover.SetDestroyTimer(destroy_timer);

				Behaviours.Add(mover);
				Behaviours.Add (new BehaviourDoDamageTarget(this,target,damage));
				Behaviours.Add (new BehaviourRotateToDirection(this));

			}

		}


	}
}

