//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Caravan
{
	public class GE_Car_Placeholder : GameElement
	{
		//public GameObject projectile;

		//public GameObject upgrade;
		//public int upgrade_cost;

		//public string target_tag;
		//public float range;
		//public float frequency;
		//public int damage;
		//public int health;

		protected override void Awake(){

			base.Awake ();

			name_string = "Car Placeholder";
		
		}

	}
}

