//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Caravan
{
	public class GE_Enemy_Basic : GameElement
	{
		//public Trajectory _trajectory;
		//public GameObject target;

		public int speed;
		public int damage;
		public int health;

		public int bounty_score;
		public int bounty_resource;

		private BehaviourTrajectoryToTarget mover_behaviour = null;
		private BehaviourDoDamageTarget damage_target_behaviour = null;

		protected override void Awake(){
			base.Awake ();

			name_string = "Basic Enemy";

			//GameObject target = FindObjectOfType<GE_Treasure_Cart> ().gameObject;

			mover_behaviour = new BehaviourTrajectoryToTarget (this, null, null, speed );
			Behaviours.Add (mover_behaviour);

			damage_target_behaviour = new BehaviourDoDamageTarget (this, null, damage);
			Behaviours.Add (damage_target_behaviour);

			Behaviours.Add (new BehaviourHealthPoints(this,health));
			Behaviours.Add (new BehaviourBounty (this,bounty_score, bounty_resource));

		}

		public void SetParameters(Trajectory trajectory, GameObject target){
			if (mover_behaviour != null) {
				mover_behaviour.TrajectoryMover.SetTrajectory (trajectory);
				mover_behaviour.TargetMover.Target = target;
			}

			if (damage_target_behaviour != null)
				damage_target_behaviour.SetTarget (target);
		}

	}
}

