//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Caravan
{
	public class GE_Gatherer_Cart : GameElement
	{
		public float gather_frequency;
		public int gather_amount;
		public int health;

		protected override void Awake(){

			base.Awake ();

			name_string = "Gatherer Car";

			Behaviours.Add (new BehaviourGatherer (this, gather_frequency, gather_amount));
			Behaviours.Add (new BehaviourPlayerHealthPoints (this));
			//Behaviours.Add (new BehaviourUpgradable(this, upgrade, upgrade_cost));

		}

	}
}

