//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Caravan
{
	public class GE_Manual_Projectile : GameElement
	{
		//public float speed;
		public float destroy_timer;
		public string target_tag;
		public int damage;
		
		protected override void Awake(){
			base.Awake ();
			
			name_string = "Manual Projectile";


		}

		protected override void Start(){
			base.Start ();

			Behaviours.Add (new BehaviourRotateToDirection(this));

			BehaviourDoDamageTag damage_tag = new BehaviourDoDamageTag (this, target_tag, damage);
			damage_tag.SetDestroyTimer (destroy_timer);

			Behaviours.Add (damage_tag);


		}
		
		public void SetDamage(int dam){
			damage = dam;
		}

	}
}

